config/routes.rb
Daydesk::Application.routes.draw do
 
  resources :suppliers do
  	resources :services
  end

  root :to => "suppliers#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  resources :enquiries

  resources :bookings

end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :supplier
  has_many :bookings
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @supplier = Supplier.find(params[:supplier_id])
    @services = @supplier.services.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @supplier = Supplier.find(params[:supplier_id])
   
  end

  # GET /services/new
  def new
    @supplier = Supplier.find(params[:supplier_id])
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
    @supplier = Supplier.find(params[:supplier_id])
  end

  # POST /services
  # POST /services.json
  def create
    @supplier = Supplier.find(params[:supplier_id])
    @service = @supplier.services.create(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to supplier_path(@supplier), notice: 'Service was successfully created.' }
        format.json { render action: 'show', status: :created, location: @service }
      else
        format.html { render action: 'new' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to supplier_service_path(@supplier, @service), notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @supplier = Supplier.find(params[:supplier_id])
    @service.destroy
    respond_to do |format|
      format.html { redirect_to supplier_services_url(@supplier) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @supplier = Supplier.find(params[:supplier_id])
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:supplier_id, :desktype, :deskrate, :wifi, :wifilimit, :printing, :printingdesc, :sendfax, :receivefax)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= simple_form_for([@supplier, @service]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :desktype %>
    <%= f.input :deskrate %>
    <%= f.input :wifi %>
    <%= f.input :wifilimit %>
    <%= f.input :printing %>
    <%= f.input :printingdesc %>
    <%= f.input :sendfax %>
    <%= f.input :receivefax %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h3>Edit Desk Entry</h3>

<p><strong>Supplier: <%= @supplier.name %></strong></p>

<%= render 'form' %>

<%= link_to 'Show', supplier_service_path(@supplier, @service) %> |
<%= link_to 'Back', supplier_services_path(@supplier) %>

app/views/services/index.html.erb
<h1>Listing services</h1>

<table class="table">
  <thead>
    <tr>
      <th>Supplier</th>
      <th>Desktype</th>
      <th>Deskrate</th>
      <th>Wifi</th>
      <th>Wifilimit</th>
      <th>Printing</th>
      <th>Printingdesc</th>
      <th>Sendfax</th>
      <th>Receivefax</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.supplier.name %></td>
        <td><%= service.desktype %></td>
        <td><%= service.deskrate %></td>
        <td><%= service.wifi %></td>
        <td><%= service.wifilimit %></td>
        <td><%= service.printing %></td>
        <td><%= service.printingdesc %></td>
        <td><%= service.sendfax %></td>
        <td><%= service.receivefax %></td>
        <td><%= link_to 'Show', supplier_service_path(@supplier, service) %></td>
        <td><%= link_to 'Edit', edit_supplier_service_path(@supplier, service) %></td>
        <td><%= link_to 'Destroy', supplier_service_path(@supplier, service), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_supplier_service_path(@supplier) %>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to 'Back', supplier_services_path(@supplier) %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Supplier:</strong>
  <%= @service.supplier.name %>
</p>

<p>
  <strong>Desktype:</strong>
  <%= @service.desktype %>
</p>

<p>
  <strong>Deskrate:</strong>
  <%= @service.deskrate %>
</p>

<p>
  <strong>Wifi:</strong>
  <%= @service.wifi %>
</p>

<p>
  <strong>Wifilimit:</strong>
  <%= @service.wifilimit %>
</p>

<p>
  <strong>Printing:</strong>
  <%= @service.printing %>
</p>

<p>
  <strong>Printingdesc:</strong>
  <%= @service.printingdesc %>
</p>

<p>
  <strong>Sendfax:</strong>
  <%= @service.sendfax %>
</p>

<p>
  <strong>Receivefax:</strong>
  <%= @service.receivefax %>
</p>

<%= link_to 'Edit', edit_supplier_service_path(@supplier, @service) %> |
<%= link_to 'Back', supplier_services_path(@supplier) %>