config/routes.rb
Daydesk::Application.routes.draw do
 
  resources :suppliers do
  	resources :services
  end

  root :to => "suppliers#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  resources :enquiries

  resources :bookings

end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :service
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @service = Service.find(params[:service])
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    logger.info { @booking.service_id.to_s }
    respond_to do |format|
      if @booking.save
        BookingMailer.bookingsent_email(@booking).deliver
        logger.info {"Sending email back to user"}
        BookingMailer.booking_received(@booking).deliver
        logger.info {"Sending notification email to Supplier"}
        format.html { redirect_to @booking, notice: 'Thankyou, your booking was successfully sent as follows:' }
        format.json { render action: 'show', status: :created, location: @booking }
      else
        format.html { render action: 'new' }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:name, :email, :fromdate, :todate, :service_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for(@booking) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :name, label: 'Your Name', input_html: { class: 'form-control'} %>
    </div>
    <div class="form-group">
    <%= f.input :email, label: "Your Email", input_html: { class: 'form-control'} %>
	</div>
    <div class="form-group">
    <%= f.input :fromdate, input_html: { class: 'form-control'} %>
	</div>
	<div class="form-group">
    <%= f.input :todate, input_html: { class: 'form-control'} %>
	</div>
    <div class="form-group">
    <%= f.input :service_id, as: :hidden, input_html: {value: @service.id} %>
    </div>
    <p>&nbsp;</p>
    <%= f.button :submit, :class => 'btn btn-success', label: 'Send Booking' %>
<% end %>

app/views/bookings/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<h3>Edit Booking</h3>
			<%= render 'form' %>
			<p>&nbsp;</p>
			<%= link_to 'Show all bookingss', bookings_path, :class => 'btn btn-success' %> 
		</div>
	</div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h3>Listing Bookings</h3>

      <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>From Date</th>
            <th>To Date</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @bookings.each do |booking| %>
            <tr>
              <td><%= booking.name %></td>
              <td><%= booking.email %></td>
              <td><%= booking.fromdate %></td>
              <td><%= booking.todate %></td>
              <td><%= link_to 'Show', enquiry %></td>
              <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
              <td><%= link_to 'Destroy', enquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Booking', new_booking_path, :class => 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<h4>Send Booking to <%= @service.supplier.name %></h4>
			<h5>For their <%= @service.desktype %> service </h5>
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/bookings/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10">
			<h3>Booking Detail</h3>

				<p>
				  <strong>Name:</strong>
				  <%= @booking.name %>
				</p>

				<p>
				  <strong>Email:</strong>
				  <%= @booking.email %>
				</p>

				<p>
				  <strong>From Date:</strong>
				  <%= @booking.fromdate %>
				</p>
				<p>
				  <strong>To Date:</strong>
				  <%= @booking.todate %>
				</p>
				<p>&nbsp;</p>
				<%= link_to 'Show all bookings', bookings_path, :class => 'btn btn-success' %>
		</div>
	</div>
</div>