config/routes.rb
Daydesk::Application.routes.draw do
 
  resources :suppliers do
  	resources :services
  end

  root :to => "suppliers#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  resources :enquiries

  resources :bookings

end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	has_many :services, dependent: :destroy
	accepts_nested_attributes_for :services
	has_many :enquiries

end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]

  # GET /suppliers
  # GET /suppliers.json
  def index
    @suppliers = Supplier.all
  end

  # GET /suppliers/1
  # GET /suppliers/1.json
  def show
    @services = @supplier.services
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new
  end

  # GET /suppliers/1/edit
  def edit
  end

  # POST /suppliers
  # POST /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to @supplier, notice: 'Supplier was successfully created.' }
        format.json { render action: 'show', status: :created, location: @supplier }
      else
        format.html { render action: 'new' }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1
  # PATCH/PUT /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to @supplier, notice: 'Supplier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.json
  def destroy
    @supplier.destroy
    respond_to do |format|
      format.html { redirect_to suppliers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplier_params
      params.require(:supplier).permit(:name, :address1, :address2, :suburb, :postcode, :state, :contactname, :contactphone, :contactemail, :paypal, :blurb, :officetype, :pic1, :pic2, :pic3, :wifi, :wifilimit, :printing, :printingdesc, :sendfax, :receicefax, :reception, :coffee, :coffeedesc, :food, :fooddesc, :alcohol, :alcoholdesc)
    end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">

    <%= simple_form_for(@supplier, :html => {:class => 'form-horizontal' }) do |f| %>
    <%= f.error_notification %>

    <div class="form-group">
    <%= f.input :name, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :address1, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :address2, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :suburb, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :postcode, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :state, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :contactname, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :contactphone, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :contactemail, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :paypal, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :blurb, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :officetype, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :wifi %>
    </div>

    <div class="form-group">
    <%= f.input :wifilimit, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :printing %>
    </div>

    <div class="form-group">
    <%= f.input :printingdesc, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :sendfax %>
    </div>

    <div class="form-group">
    <%= f.input :receivefax %>
    </div>

    <div class="form-group">
    <%= f.input :reception, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :coffee %>
    </div>

    <div class="form-group">
    <%= f.input :coffeedesc, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :food %>
    </div>

    <div class="form-group">
    <%= f.input :fooddesc, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :alcohol, label_html: { class: 'inline'} %>
    </div>

    <div class="form-group">
    <%= f.input :alcoholdesc, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :pic1, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :pic2, input_html: { class: 'form-control'} %>
    </div>

    <div class="form-group">
    <%= f.input :pic3, input_html: { class: 'form-control'} %>
    </div>
  
    <%= f.button :submit, :class => 'btn btn-warning btn-sm' %>

    <% end %>
    <p>&nbsp;</p>
    </div>
  </div>
</div>

app/views/suppliers/edit.html.erb
<h3>Edit Supplier</h3>

<%= render 'form' %>

<%= link_to 'Show', @supplier, :class => 'btn btn-success btn-sm' %> 
<%= link_to 'Back', suppliers_path, :class => 'btn btn-success btn-sm' %>

app/views/suppliers/index.html.erb
<div class="container">
<h3>Spaces</h3>  
    <% @suppliers.each do |supplier| %>
      <div class="row row-index">
        <div class="col-md-3">
        <strong><%= supplier.name %></strong><br>
          <%= supplier.address1 %><br>
          <% if supplier.address2? %>
          <%= supplier.address2 %><br>
          <% end %>
          <%= supplier.suburb %> <%= supplier.state %> <%= supplier.postcode %><br><br>  
        <%= image_tag supplier.pic1, :class => 'list-pic' %>  
        </div>
        <div class="col-md-3">
          <p><strong>Summary:</strong><br>
          <%= supplier.officetype %><br>
          <i class="fa fa-signal"></i> <% if supplier.wifi %><%= supplier.wifilimit %><% else %>No<% end %><br>
          <i class="fa fa-print"></i> <% if supplier.printing %><%= supplier.printingdesc %><% else %>No<% end %><br>
          <i class="fa fa-coffee"></i> <% if supplier.coffee %><%= supplier.coffeedesc %><% else %>No<% end %><br>
          <i class="fa fa-cutlery"></i> <% if supplier.food %><%= supplier.fooddesc %><% else %>No<% end %><br>
          <i class="fa fa-beer"></i> <% if supplier.alcohol %><%= supplier.alcoholdesc %><% else %>No<% end %><br>
          <i class="fa fa-user"></i> <%= supplier.reception %>
        </p>
        </div>
        <div class="col-md-3">
          <%= simple_format h truncate(supplier.blurb, :length => 200) %> <%= link_to 'Details & Booking', supplier, :class => 'btn btn-xs btn-primary' %>
        </div>
        <div class="col-md-2"><%= link_to 'Edit', edit_supplier_path(supplier), :class => 'btn btn-warning btn-xs' %> <%= link_to 'Destroy', supplier, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-xs' %></div>
       
        <div class="col-md-1"></div>
      </div>
    <% end %>
    <p>&nbsp;</p>
<%= link_to 'New Supplier', new_supplier_path, :class => 'btn btn-success btn-xs' %>    
</div>

app/views/suppliers/new.html.erb
<h1>New supplier</h1>

<%= render 'form' %>

<%= link_to 'Back', suppliers_path %>

app/views/suppliers/show.html.erb
<div class="container">
  <p>&nbsp;</p>
 <%= link_to 'Back to List', suppliers_path, class: 'btn btn-success btn-xs' %> 
 <%= link_to 'Edit Profile', edit_supplier_path(@supplier), class: 'btn btn-warning btn-xs' %> 
 <%= link_to 'Add a Desk Listing', new_supplier_service_path(@supplier), class: 'btn btn-warning btn-xs' %>
 <h3><%= @supplier.name %></h3> 
 
  <div class="row">
    <div class="col-md-3">
        <p>
          <strong>Location:</strong><br>
          <%= @supplier.address1 %><br>
          <% if @supplier.address2? %>
          <%= supplier.address2 %><br>
          <% end %>
          <%= @supplier.suburb %> <%= @supplier.state %> <%= @supplier.postcode %>
        </p>

        <p>
          <strong>Contact:</strong><br>
          <% if @supplier.contactname? %>
          <%= @supplier.contactname %><br>
          <% end %>
          <%= @supplier.contactphone %><br>
          <%= @supplier.contactemail %>
        </p>

        <p><strong>Summary:</strong><br>
          <%= @supplier.officetype %><br>
          <i class="fa fa-signal"></i> <% if @supplier.wifi %><%= @supplier.wifilimit %><% else %>No<% end %><br>
          <i class="fa fa-print"></i> <% if @supplier.printing %><%= @supplier.printingdesc %><% else %>No<% end %><br>
          <i class="fa fa-coffee"></i> <% if @supplier.coffee %><%= @supplier.coffeedesc %><% else %>No<% end %><br>
          <i class="fa fa-cutlery"></i> <% if @supplier.food %><%= @supplier.fooddesc %><% else %>No<% end %><br>
          <i class="fa fa-beer"></i> <% if @supplier.alcohol %><%= @supplier.alcoholdesc %><% else %>No<% end %><br>
          <i class="fa fa-user"></i> <%= @supplier.reception %><br><br>
          <td><%= link_to 'Enquire', new_enquiry_path(:supplier => @supplier.id), :class => 'btn btn-success btn-xs' %></td>
        </p>
    </div>
    <div class="col-md-6">
      <%= image_tag @supplier.pic1, class: 'show-pic' %>
      <p>&nbsp;</p>
      <table class="table">
        <thead>
          <tr>
            <th>Desk Type</th>
            <th>Desk Rate</th>
            <th>Reservation</th>
          </tr>
        </thead>
        <tbody>
          <% @services.each do |service| %>
          <tr>
            <td><%= service.desktype %></td> 
            <td><%= service.deskrate %></td>
            <td><%= link_to 'Reserve a Desk', new_booking_path(:service => service.id), :class => 'btn btn-success btn-xs' %></td>

          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-9">
      <p><strong>About the space</strong></p>
      <%= @supplier.officetype %><br><br>
      <%= simple_format h @supplier.blurb %>
    </div>
  </div>
  
 

</div>