config/routes.rb
Daydesk::Application.routes.draw do
 
  resources :suppliers do
  	resources :services
  end

  root :to => "suppliers#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  resources :enquiries

  resources :bookings

end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
	belongs_to :supplier
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  before_action :set_enquiry, only: [:show, :edit, :update, :destroy]

  # GET /enquiries
  def index
    @enquiries = Enquiry.all
  end

  # GET /enquiries/1
  def show
  end

  # GET /enquiries/new
  def new
    @supplier = Supplier.find(params[:supplier])
    @enquiry = Enquiry.new
  end

  # GET /enquiries/1/edit
  def edit
  end

  # POST /enquiries
  def create
    @enquiry = Enquiry.new(enquiry_params)
    logger.info { @enquiry.supplier_id.to_s }
    respond_to do |format|
      if @enquiry.save
        EnquiryMailer.enquiry_email(@enquiry).deliver
        logger.info {"Sending email back to user"}
        EnquiryMailer.enquiry_received(@enquiry).deliver
        logger.info {"Sending notification email to Supplier"}
        format.html { redirect_to @enquiry, notice: 'Thankyou, your enquiry was successfully sent as follows:' }
        format.json { render action: 'show', status: :created, location: @enquiry }
      else
        format.html { render action: 'new' }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enquiries/1
  def update
    if @enquiry.update(enquiry_params)
      redirect_to @enquiry, notice: 'Enquiry was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /enquiries/1
  def destroy
    @enquiry.destroy
    redirect_to enquiries_url, notice: 'Enquiry was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enquiry
      @enquiry = Enquiry.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def enquiry_params
      params.require(:enquiry).permit(:name, :email, :message, :supplier_id)
    end
end

app/views/enquiries/_form.html.erb
<%= simple_form_for(@enquiry) do |f| %>
  <%= f.error_notification %>

    <div class="form-group">
    <%= f.input :name, label: 'Your Name', input_html: { class: 'form-control'} %>
    </div>
    <div class="form-group">
    <%= f.input :email, label: "Your Email", input_html: { class: 'form-control'} %>
	</div>
    <div class="form-group">
    <%= f.input :message, input_html: { class: 'form-control'} %>
	</div>
    <div class="form-group">
    <%= f.input :supplier_id, as: :hidden, input_html: {value: @supplier.id} %>
    </div>
    <p>&nbsp;</p>
    <%= f.button :submit, :class => 'btn btn-success', label: 'Send Enquiry' %>
  
<% end %>

app/views/enquiries/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<h1>Edit Enquiry</h1>
			<%= render 'form' %>
			<p>&nbsp;</p>
			<%= link_to 'Show all enquiries', enquiries_path, :class => 'btn btn-success' %> 
		</div>
	</div>
</div>

app/views/enquiries/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h1>Listing enquiries</h1>

      <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @enquiries.each do |enquiry| %>
            <tr>
              <td><%= enquiry.name %></td>
              <td><%= enquiry.email %></td>
              <td><%= link_to 'Show', enquiry %></td>
              <td><%= link_to 'Edit', edit_enquiry_path(enquiry) %></td>
              <td><%= link_to 'Destroy', enquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Enquiry', new_enquiry_path, :class => 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/enquiries/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<h4>Send Enquiry to <%= @service.supplier.name %></h4>
			<h5>About their <%= @service.desktype %> service </h5>
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/enquiries/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10">
			<h3>Enquiry Detail</h3>

				<p>
				  <strong>Name:</strong>
				  <%= @enquiry.name %>
				</p>

				<p>
				  <strong>Email:</strong>
				  <%= @enquiry.email %>
				</p>

				<p>
				  <strong>Message:</strong>
				  <%= @enquiry.message %>
				</p>
				<p>&nbsp;</p>
				<%= link_to 'Show all enquiries', enquiries_path, :class => 'btn btn-success' %>
		</div>
	</div>
</div>